import { IPackingList } from "../packingList/PackingList";

export interface ILabelValue {
  label: string;
  value: string;
}

export const travelPackingListsDefaultValues: IPackingList = {
  basics: {
    travelAids: [
      "Pleasure Reading",
      "Chewing Gum",
      "Snacks",
      "Water Bottle",
      "Earplugs",
      "Sleeping Mask",
      "Travel Pillow",
      "Motion Sickness Remedy",
      "Sleeping Pills",
      "Anxiety Medication",
    ],
    funds: ["Wallet", "Cash", "Credit Cards"],
    travelInfo: [
      "Passport",
      "Visa",
      "Driver's Licence",
      "Maps",
      "Travel Tickets",
      "Travel Guides",
    ],
  },
  clothes: {
    basics: [
      "Underwear",
      "Socks",
      "Undershirts",
      "Bras",
      "Pantyhose",
      "Sleepwear",
      "Robe",
    ],
    dressy: [
      "Dress Shirts",
      "Blazers",
      "Slacks",
      "Skirts",
      "Dresses",
      "Suits",
      "Tuxedo",
    ],
    outerwear: ["Jackets", "Raincoats"],
    casual: [
      "T-Shirts",
      "Tank Tops",
      "Sweatshirts",
      "Jeans",
      "Exercise Clothing",
    ],
    footwear: ["Athletic Shoes", "Leisure Shoes", "Dress Shoes", "Slippers"],
    accessories: [
      "Belts",
      "Ties",
      "Wristwatches",
      "Jewelry",
      "Sunglasses",
      "Reading Glasses",
    ],
  },
  hygiene: {
    hygiene: [
      "Toothbrush",
      "Toothpaste",
      "Dental Floss",
      "Mouthwash",
      "Soap",
      "Washcloth",
      "Deodorant",
      "Shampoo",
      "Conditioner",
      "Brush",
      "Comb",
      "Curling Iron",
      "Flat Iron",
      "Styling Products",
      "Hair Accessories",
      "Mirror",
      "Cleanser",
      "Sunscreen",
      "Moisturizer",
      "Lip Balm",
      "Contact Lenses",
      "Saline Solution",
      "Shaving Cream",
      "Razor",
      "Perfume",
      "Makeup",
      "Makeup Remover",
      "Birth Control",
      "Feminine Hygiene",
      "Nail Clippers",
      "Nail File",
      "Hand Wipes",
      "Tissues",
      "Cotton Swabs",
      "Tweezers",
      "Insect Repellent",
      "Medications",
      "Pain Reliever",
      "Vitamins",
      "First Aid",
      "Band Aids",
      "Towels",
    ],
  },
  miscellaneous: {
    documents: [
      "Emergency Contact Info",
      "Medical Insurance Card",
      "Prescriptions",
      "Travel Insurance",
      "Car Insurance Card",
    ],
    bags: ["Backpack", "Purse", "Tote", "Plastic Bags"],
    miscellaneous: [
      "Umbrella",
      "House Keys",
      "Luggage Tags",
      "Hospitality Gifts",
      "Journal",
    ],
    technology: [
      "Cell Phone",
      "Cell Phone Charger",
      "Laptop",
      "Laptop Charger",
      "Camera",
      "Camera Charger",
      "Headphones",
      "Batteries",
      "Flashlight",
    ],
    work: ["Work Documents", "Office Supplies", "Business Cards", "Laptop Bag"],
  },
};

export const travelPackingListsWarmValues: IPackingList = {
  basics: {
    travelAids: [],
    funds: [],
    travelInfo: [],
  },
  clothes: {
    basics: [],
    dressy: [],
    outerwear: [],
    casual: ["Shorts", "Swimsuits"],
    footwear: ["Sandals"],
    accessories: [],
  },
  hygiene: {
    hygiene: [],
  },
  miscellaneous: {
    documents: [],
    bags: [],
    miscellaneous: ["Beach Towel", "Beach Ball"],
    technology: [],
    work: [],
  },
};

export const travelPackingListsColdValues: IPackingList = {
  basics: {
    travelAids: [],
    funds: [],
    travelInfo: [],
  },
  clothes: {
    basics: [],
    dressy: ["Sweaters"],
    outerwear: ["Coats", "Skiwear"],
    casual: [],
    footwear: [],
    accessories: ["Hats", "Gloves", "Scarves"],
  },
  hygiene: {
    hygiene: [],
  },
  miscellaneous: {
    documents: [],
    bags: [],
    miscellaneous: [],
    technology: [],
    work: [],
  },
};
